[ADR-0004] Auth Strategy: Passport vs OpenID Connect
wellcomecollection/identity pull request #52
Opened 2021-01-14 17:09 UTC by ajrussellaudio

2021-01-15 09:51 UTC, danielgrant requested changes
I'll let @stephenwf @ajrussellaudio @ionab make the decision on this one, but it sounds like sticking with passport-auth0 is the path of least resistance here. We already have it integrated and Auth0 will continue to support the library for the time being, so I don't see any pressing need to switch to express-openid-connect unless someone else can provide one.

2021-01-15 11:14 UTC, ionab submitted a review, later dismissed
Looks reasonable to me, I think the decision should be to stick with Passport-Auth0, as we are using KOA.

2021-01-15 12:55 UTC, stephenwf approved these changes
I agree, there is not a considerable downside to sticking with koa-passport 👍

2021-01-15 12:55 UTC, stephenwf commented on docs/adr/0004-auth-strategy--passport-vs-openid.md
> +- The koa-passport repo has not been updated since July 2019, and the package not published since April 2019. As it is a wrapper around the main Passport library, it is not clear if there are securit
We can, if required, update the passport dependency independently.

2021-01-15 12:55 UTC, stephenwf commented on docs/adr/0004-auth-strategy--passport-vs-openid.md
> +- The Node.js server uses the Koa framework, but the OpenID Connect SDK is written for Express. Express middleware is not directly compatible with Koa, although solutions to achieve compatibility do
This is a small one, but we do use the passport to enable local development, which would be lost or require re-work.

2021-01-15 14:28 UTC, stephenwf approved these changes

2021-01-18 09:21 UTC, danielgrant submitted a review, later dismissed

2021-01-18 09:54 UTC, danielgrant approved these changes

2021-01-18 09:55 UTC, merged