Add Current Password verification field to Change Password form
wellcomecollection/identity pull request #59
Opened 2021-01-18 17:41 UTC by ajrussellaudio

The validation logic here seems ok to me, but the UX isn't great as the new password validation happens before the user has started typing.

The logic behind showing that "not valid" message is quite fiddly, and I'd rather write some unit tests than fiddle with it any further. Installing and configuring a UI testing framework isn't a trivial piece of work, and it shouldn't hold up this ticket. This PR meets the requirements as defined.

2021-01-18 18:04 UTC, ionab requested changes
Can we show the password policy on the form below the type new password? (See bullet points on registration page). Or double check with Ville that this isn't required?
I also understood the requirement to be that a user must confirm their current password to be able to update their password... See JIRA ticket WS-31.

2021-01-19 09:27 UTC, ajrussellaudio commented
Thanks @ionab. The bullet points were an oversight, now fixed.

I'll need to check with UX on those requirements. I'd been working on the assumption that we'd send all three fields to the API at the same time, but you're absolutely right, that's not what the requirements state. Checking a password as the user types doesn't seem great for performance or security.

2021-01-19 11:45 UTC, ajrussellaudio commented
@ionab During discussion of the above issue, it was pointed out that there is the opportunity to verify the password server-side before making the call to the 'update password' endpoint. That would probably take place in `src/routes/api/update-password.ts`, but should be done as part of WS-101 and not this ticket. As per the wireframes, all three fields in one screen is what we're looking for here.

2021-01-20 10:02 UTC, ionab approved these changes

2021-01-20 10:40 UTC, merged